### ISSUE TITLE
Running into the following error: Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by arnavw96** [lileipisces/Sentires-Guide#5]
Hey, I was trying to run your code to generate the FOS triplets. I generated the product2json.pickle and record.per.row.txt files using python lei/0.format.py this command, but was running into the following error while running java -jar thuir-sentires.jar -t pre -c lei/1.pre

0    INFO  2023-04-10 20:12:33 Context - Use /content/drive/MyDrive/English-Jar as home directory
Exception in thread "main" java.lang.NullPointerException
	at edu.thuir.sentires.utility.Preprocessing.preprocess(Preprocessing.java:82)
	at edu.thuir.sentires.utility.Preprocessing.preprocess(Preprocessing.java:44)
	at edu.thuir.sentires.program.Application.preprocess(Application.java:90)
	at edu.thuir.sentires.program.Application.main(Application.java:160)

Could you maybe help resolve this? Would appreciate any leads!

**Comment by arnavw96** [comment]
To be more specific; I'm running this on google colab as well as a windows machine

**Comment by Milin0802** [comment]
> Hey, I was trying to run your code to generate the FOS triplets. I generated the product2json.pickle and record.per.row.txt files using python lei/0.format.py this command, but was running into the following error while running java -jar thuir-sentires.jar -t pre -c lei/1.pre
> 
> 0 INFO 2023-04-10 20:12:33 Context - Use /content/drive/MyDrive/English-Jar as home directory Exception in thread "main" java.lang.NullPointerException at edu.thuir.sentires.utility.Preprocessing.preprocess(Preprocessing.java:82) at edu.thuir.sentires.utility.Preprocessing.preprocess(Preprocessing.java:44) at edu.thuir.sentires.program.Application.preprocess(Application.java:90) at edu.thuir.sentires.program.Application.main(Application.java:160)
> 
> Could you maybe help resolve this? Would appreciate any leads!

May I ask if your problem was finally solved? And how was it solved? Thank you!

**Comment by lileipisces** [comment]
Hi, recently someone reported the same issue to me and successfully fixed it by using the newest [version](https://github.com/evison/Sentires).

**Comment by Milin0802** [comment]
Thanks very much!



 李熙_中国人民大学
  ***@***.***
  




---- Replied Message ----
From  Lei ***@***.***> Date  07/9/2024 10:59 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [lileipisces/Sentires-Guide] Running into the following error: Exception in thread "main" java.lang.NullPointerException (Issue #5)  

Hi, recently someone reported the same issue to me and successfully fixed it by using the newest version.
